name: Build on Linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Debug Build Output
        run: find . -name '*.so'

      - name: Prepare Package folder
        run: |
          mkdir -p Package/UserPlugins
          cp ./build/reaper_csurf_integrator.so Package/UserPlugins/
          cp -r Scripts Package/
          cp -r CSI Package/
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_${{ github.ref_name }}_linux
          path: Package
