on:
  push:
    tags: [ 'v*' ]

jobs:
  build-macos-intel:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Debug Build Output
        run: find . -name '*.dylib'

      - name: Prepare Package folder
        run: |
          mkdir -p Package/UserPlugins
          cp ./build/reaper_csurf_integrator.dylib Package/UserPlugins/
          cp -r Scripts Package/
          cp -r CSI Package/
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_${{ github.ref_name }}_mac_intel
          path: Package

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CSI_${{ github.ref_name }}_mac_intel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Debug Build Output
        run: find . -name '*.dylib'

      - name: Prepare Package folder
        run: |
          mkdir -p Package/UserPlugins
          cp ./build/reaper_csurf_integrator.dylib Package/UserPlugins/
          cp -r Scripts Package/
          cp -r CSI Package/
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_${{ github.ref_name }}_mac_arm
          path: Package

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CSI_${{ github.ref_name }}_mac_arm.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Debug Build Output
        run: dir /s *.dll
        shell: cmd

      - name: Prepare Package folder
        run: |
          mkdir Package\UserPlugins
          copy .\build\Release\reaper_csurf_integrator.dll Package\UserPlugins\
          xcopy Scripts Package\Scripts\ /E /I
          xcopy CSI Package\CSI\ /E /I
        shell: cmd

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_${{ github.ref_name }}_win
          path: Package

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CSI_${{ github.ref_name }}_win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Debug Build Output
        run: find . -name '*.so'

      - name: Prepare Package folder
        run: |
          mkdir -p Package/UserPlugins
          cp ./build/reaper_csurf_integrator.so Package/UserPlugins/
          cp -r Scripts Package/
          cp -r CSI Package/
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CSI_${{ github.ref_name }}_linux
          path: Package

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CSI_${{ github.ref_name }}_linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

